version: "3.8"
services:
  bot:
    image: lunarmagpie/kosuzu:latest
    restart: always
    network_mode: bridge
    depends_on:
      - db
    links:
      - db
    environment:
      DATABASE: kozusa
      DATABASE_PORT: 5432
      DATABASE_HOST: db
      DATABASE_USER: kozusa
      DATABASE_PASSWORD: kozusa
    env_file:
      - .env

  db:
    image: postgres
    restart: always
    network_mode: bridge
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: kozusa
      POSTGRES_DB: kozusa
      POSTGRES_PASSWORD: kozusa

volumes:
  db-data:
    driver: local
